### PR TITLE
Update README to provide some help for Heroku users

### PR DESCRIPTION
**Pull request by SilasSpet**
The error mentioned in the changes happened to me. Took me a while to find the root cause of the problem since it only happened in production and the error message isn't that helpful. I think the changes in the README are pretty self-explanatory but if you have any questions I'd be happy to answer them.

### CODE REVIEW

**Comment by janko** [comment]
Thank you for the PR. I took it a step further and made rodauth-rails automatically pick up the secret key base from `$SECRE_KEY_BASE` in https://github.com/janko/rodauth-rails/commit/47059bb1d842064ce2b129a335d324a0f0f72d1c. Could you test whether the current `master` branch works for you? Afterwards I'll release a new version 😉

**Comment by SilasSpet** [comment]
I just removed my `hmac_secret` fix, deployed the current `master` to staging and added & authenticated via WebAuthn. Works perfectly! 🎉

**Comment by janko** [comment]
Great to hear! I've just released version 0.7.0 with this fix.

**Comment by SilasSpet** [comment]
Updated and deployed to production 🚀 Thanks for the quick fix!

**Pull request closed without merging**
