### PR TITLE
Add rspec fixtures

### PR DESCRIPTION
**Pull request by benkoshy**
* Work in progress. Unfinished.

### CODE REVIEW

**Comment by janko** [comment]
I would prefer draft pull requests to be used only in rare cases where the PR author would like to get early feedback, in this case it would be easier for me to just receive the PR when it's finished.

**Comment by benkoshy** [comment]
I'll resubmit

**Comment by janko** [comment]
I would like to get a fix for this released, so that installing Rodauth doesn't create a `test/` directory for RSpec users. Are you still planning to finish this?

**Comment by benkoshy** [comment]
Absolutely - am committed to seeing this through after starting it.  Got stuck -- hence the delay. If i can't solve it by close of Monday,  i will ask for your assistance.

**Comment by benkoshy** [comment]
@janko I don't know why it's not working. I tried my best. Here is the latest. for some reason, the file isn't copying. perhaps it's because i have misconfiugred the thor actions?

**Comment by janko** [comment]
I think `hook_for` requires you to create a new generator using a certain class naming convention, which would take over from the point where `hook_for` was called.

Let's use the model generator as an example. As I understood, the entry point is [`Rails::Generators::ModelGenerator`](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/model/model_generator.rb), which declares `hook_for :orm`. This detects [`ActiveRecord::Generators::ModelGenerator`](https://github.com/rails/rails/blob/main/activerecord/lib/rails/generators/active_record/model/model_generator.rb), which then continues defining the generator commands (which are IMO all public methods), and defines a `hook_for :test_framework`. This then picks up [`TestUnit::Generators::ModelGenerator`](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/test_unit/model/model_generator.rb), which defines creating the test file, and declares `hook_for :fixture_replacement` after that (since creating the test file isn't affected by fixture replacement), but before creating the fixture file, so that it can override that part. When using FactoryBot, [`FactoryBot::Generators::ModelGenerator`](https://github.com/thoughtbot/factory_bot_rails/blob/main/lib/generators/factory_bot/model/model_generator.rb) gets picked up, which overrides fixture creation with its own implementation.

In our case, if we would use `hook_for :test_framework` on `Rodauth::Rails::Generators::InstallGenerator`, I think we'd need to define a new `RSpec::Generators::InstallGenerator` generator that overrides the fixture creation part. That seems like an overkill, and I think we should only define hook generators for libraries that we own, because in this case we'd be accidentally overriding RSpec's built-in [install generator](https://github.com/rspec/rspec-rails/blob/main/lib/generators/rspec/install/install_generator.rb).

-------

So, I recommend using a simple conditional, for example `if defined?(RSpec::Rails)` inside the generator method. I see you're using a conditional based on `config.generators.options[:test_framework]`, why are you expecting it to be an empty string, isn't it supposed to be `:rspec`?

**Comment by janko** [comment]
> I am unable to re-open the branch

It's probably because yesterday I renamed the `master` branch to `main`.

**Comment by benkoshy** [comment]
This explanation helps point the way -  perhaps a little too much ;)  - please allow me to digest and finish off this PR tomorrow and day after.

**Comment by janko** [comment]
Yeah, I realize now that I could have made the pointers much simpler and more vague. Basically, we don't need `hook_for`, and re-check your conditional for RSpec 😉

**Pull request closed without merging**
