### PR TITLE
Fix that the sequel migration was made irreversible by my previous change

### PR DESCRIPTION
**Pull request by Empact**

### CODE REVIEW

**Comment by Empact** [comment]
Follow-up to https://github.com/janko/rodauth-rails/pull/117

**Comment by Empact** [comment]
This needs work as sequel migration doesn't implement `reversible`.

**Comment by Empact** [comment]
Options include:
* Using `up` and `down` in a single migration, which will produce a good amount of duplication
* Splitting out the citext enabling to a different migration, so that `up` and `down` do not produce duplication
* Commenting an instruction to enable citext

**Comment by janko** [comment]
At this time I would go with the 3rd option, adding a comment to enable citext.

I'm preparing to add support for database functions soonish, and that will probably require splitting `change` to `up` & `down`, so I can incorporate enabling the citext extension after those changes.

**Comment by janko** [comment]
I figured out a workaround where we get to keep the `change` block, by rescuing `NoMethodError` when reverting the migration. It's a bit of a hack, but at least it will work until we add explicit `down` blocks.

**Pull request closed without merging**
